query getUserPosts($page: Int!) {
  user(username: "tinaciousdesign") {
    publication {
      _id
      title
      posts(page: $page) {
        _id
        title
        contentMarkdown
        slug
        tags {
          _id
          name
          slug
        }
      }
    }
  }
}
